### ISSUE TITLE
ui5-codecompletion install throws error 404

### ISSUE THREAD

**Issue by Rob077** [vobu/ui5-codecompletion#11]
When using install option _ui5-codecompletion instal_l an error 404 occurs:

> downloading https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.61.2.zip
> Remote file at https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.61.2.zip doesn't seem to exist. Server responded with status code 404!

**Comment by MaximilienFourmyBeyond** [comment]
Got the same issue and it was fixed by providing the url of one of the releases available here:
https://openui5.org/releases/

So in my case, I use the version 1.60 which is available by providing the URL in the command like this:
ui5-codecompletion install -f https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.60.12.zip

Maybe the default version in ui5-codecompletion could be updated though..
(The best would be to have a "latest" or "stable" runtime url provided by openUI5)

**Comment by vobu** [comment]
the workaround @MaximilienFourmyBeyond describes above is spot on. would love to have the automatic download point to `latest` UI5 version, but that symlink/tag doesn't exist yet. 
best, v.

**Comment by rsletta** [comment]
Hi @vobu. I have started a small project to create a api that returns url as a string, to the latest version of OpenUI5. I'll keep you updated about the progress.

https://get-latest-openui5-version.firebaseapp.com/api/v1/latest?type=runtime

Possible types: sdk | runtime | runtimeMobile

**Comment by MaximilienFourmyBeyond** [comment]
Hi,
Another solution to get the last release of openUI5 is provided by @pavelkornev here :
https://openui5.slack.com/archives/CABT2CKK6/p1556606884009000?thread_ts=1556290824.007800&cid=CABT2CKK6

`(async () => {
    const response = await fetch("https://api.github.com/repos/SAP/openui5/releases/latest");
    const data = JSON.parse(await response.text());
    const files = data.assets.map(({ browser_download_url }) => browser_download_url);
    console.log(files);
})();`

**Comment by vobu** [comment]
Hi, thanks for the heads-up and suggestions, you both @rsletta @MaximilienFourmyBeyond !
Will implement a "latest" retrieval once I find the time.
